@startuml 02color

folder Img{
    class 金字塔{
<img src="https://icooon-mono.com/i/icon_10105/icon_101051_64.png">
    }
    class 樹木図 {
        <img src="https://icooon-mono.com/i/icon_14637/icon_146371_64.png">
    }
     金字塔 *-* 樹木図
}

class フレーズ
フレーズ ---> 金字塔

class 物の意味
フレーズ -> 物の意味
物の意味 ---> 金字塔

class デザイン {
  <img src="https://icooon-mono.com/i/icon_13177/icon_131771_64.png">
}
デザイン --> 金字塔
デザイン ..> 樹木図

class 仕草 {
  <img src="https://icooon-mono.com/i/icon_11642/icon_116421_64.png" >
}
  
仕草 ---> 樹木図

class 色 {
    <img src="https://icooon-mono.com/i/icon_12927/icon_129271_64.png" >
}
色 --> 樹木図
色 ..> 金字塔




@enduml