@startuml 02color

folder Img{
    class ピラミッド
    class 樹木図
}

class フレーズ
フレーズ ---> ピラミッド

class 物の意味
フレーズ -> 物の意味
物の意味 ---> ピラミッド

class デザイン
デザイン --> ピラミッド
デザイン ..> 樹木図

class 仕草
仕草 ---> 樹木図

class 色
色 --> 樹木図
色 ..> ピラミッド




@enduml
