@startuml resonaunce

namespace 阻害音 {
    namespace ex {
        class 5
    } 
    class 濁点がつけられる
    
    class 阻害音判定
    濁点がつけられる --> 阻害音判定
    
    class 男性的 
    阻害音判定 --> 男性的

    class ki

    class 角ばった
    ki --> 角ばった
    
}



namespace 共鳴音 {
    namespace ex {
        class m
        class n
        class y
        class r
        class w
        class マナヤラワ
    }
    class 濁点つかない
    
    class 共鳴音判定
    濁点つかない --> 共鳴音判定
    
    class 女性的 
    共鳴音判定 --> 女性的
}



namespace 濁音 {
    namespace {
        class ゴジラ
    }
    class 濁点あり

    class 口内が広がる発音
    濁点あり　--> 口内が広がる発音

    class 強大{
        大きくて
        強い
    }
    口内が広がる発音 --> 強大
}


@enduml





