
@startuml template


namespace 予備知識 {
    namespace 場所 {
        namespace どこから来たのか{}
        namespace どこへ行くのか{}
        予備知識.場所.どこから来たのか --> 予備知識.場所.どこへ行くのか
    }
    
    namespace 時間 {
        namespace 季節{}
        namespace 曜日{}
        namespace 時間帯{}
        予備知識.時間.季節 --> 予備知識.時間.曜日 
        予備知識.時間.曜日--> 予備知識.時間.時間帯
    }

    namespace 生まれ {
        namespace 親の顔 {}
    }
}
note bottom of 予備知識
iniファイル
end note


namespace 観察対象 {
  
    namespace 利き手 {
    }
    namespace 身なり {
        namespace 服装 {}
        namespace 腕時計 {}
    }
    観察対象.利き手 --> 観察対象.身なり
   
    namespace 嗜好 {
        namespace 色 {}
    }
    観察対象.身なり --> 観察対象.嗜好

   
    namespace 何に反応するか {
        namespace 色か形か {
        }
        namespace どこを見ているのか {
        }
        namespace 目の動き {
        }
        namespace セリフ {
        }
    }
    観察対象.嗜好 --> 観察対象.何に反応するか

    namespace 口癖 {

    }
    観察対象.何に反応するか --> 観察対象.口癖

}
note bottom of 観察対象
最初はベースとなるところから
だんだん深く「潜る」
end note


namespace 観察結果 {
    namespace 主義 {}
    namespace 性格 {
    }
    namespace ビッグファイブ {
        namespace 外交的 {}
        note bottom of 観察結果.ビッグファイブ.外交的
        コミュニケーションに問題がないこと?
        end note
        
        namespace 神経症傾向 {}
        note bottom of 観察結果.ビッグファイブ.神経症傾向
        外部からの刺激に敏感である
        end note
    
        namespace 誠実性 {}
        note bottom of 観察結果.ビッグファイブ.誠実性
        責任感
        end note
    
        namespace 調和性 {}
        note bottom of 観察結果.ビッグファイブ.調和性
        「バランスを取る」傾向
        協調性があるかどうか
        end note
    
        namespace 強迫観念 {}
        note bottom of 観察結果.ビッグファイブ.強迫観念
        「しなければならない」と考える傾向
        end note
    }
}


@enduml





