@startuml fruit

!include ../00target.pu

class apple


class grape {
    クリスマスツリーの装飾と似ている
    もしもこの木の実が枝に対して不当に重い場合
    自身の評価と実際の才能の差異に悩みを持っている
}
grape ---> self_evaluation.過大評価
grape ---> state.期待


class two_grape {
    二種類の木の実
}

two_grape ---> child.異性の兄弟


class Rot {
    腐った木の実
}
Rot ---> child.不出来



@enduml

