@startuml location

!include 00target.pu




class Left {

}
Left ---> time.過去
Left ---> parents.母親からの影響
Left ---> freedom.服従


class LeftUp {

}
Left --> LeftUp
LeftUp ---> parents.母親からの影響の克服


class Right {

}
Right ---> time.未来
Right ---> parents.父親からの影響
Right ---> towoman.軽蔑

class RightUp {

}
Right --> RightUp
RightUp ---> type.野心

class RightDown {

}
Right --> RightDown
RightDown ---> think.伝統主義
RightDown ---> parents.憧れと諦め


class UpperPosition {
現実に根付いていない
}
UpperPosition ---> state.想像

class BottomPosition {
この人の情緒、経験などは
過去の経験,当時の状況にのみ基づく。
漫画や小説などを描くことは少ない。
}
BottomPosition ---> state.現実
BottomPosition ---> state.過去



class overall

class Upper{
例えば葉っぱには
これからの未来への期待が
現れることもある
ex)木の実がなった絵は期待を表すなど

反対に尖った枝には
未知の攻撃に対する
防衛意識などが現れる

}

overall --> Upper
Upper --> time.未来


class Root{

}

overall --> Root
Root --> time.過去


@enduml

