@startuml baby


namespace 赤子イメージ {
    namespace ex {
        class マーミーポコパンツ
        class ムーミーマン
    }
    class p
    class m
    
    class 両唇音 {
        発音するときに唇を閉じる
    }
    p --> 両唇音
    m --> 両唇音

    class 赤ちゃんグッズに多い {
    }
    両唇音 --> 赤ちゃんグッズに多い
}




@enduml





