@startuml flow


namespace 赤子イメージ {
    namespace ex {
        class h
        class f
        class s
    }
    class 無性摩擦音

    class 鼻から息が出て行くように発音する
    無性摩擦音 --> 鼻から息が出て行くように発音する

    class 流れるイメージ
    鼻から息が出て行くように発音する --> 流れるイメージ
}




@enduml





