@startuml size




namespace 大きい音 {
    namespace ex {
    class 3
    class 4
    }
    
    
    class "形容詞の「な」" {
        ex)大きな
        }
    
    class "大きな口の開き" {
        
    }
    
    class a {
    }
    "形容詞の「な」" --> a
    "大きな口の開き" --> a

    class o {
    }
    "大きな口の開き" --> o

    class big_imagination
    a --> big_imagination
    o --> big_imagination

    class "威嚇"
    a --> "威嚇"
    o --> "威嚇"
}



namespace 小さい音 {
    
    namespace ex {
    class 1
    class 2
    
    class 9
      class u
      
        }
    
    class "形容詞の「い」" {
        ex)小さい
        }
        class "小さい口" {
        
        }
    class i {}
    "形容詞の「い」" --> i
    "小さい口" --> i




    class "拗音語" {
        赤ちゃんに対して使う言葉
        ex)小さい「よ」や「ゆ」など
    }
    "小さい口" --> "拗音語"


    class small_imagination
    i --> small_imagination
    "拗音語" --> small_imagination
  
}

namespace example {
    namespace 敬語 {
        class です
        
        class ました

    }
}


@enduml
