@startuml 04furniture

partition "家具類" {
    partition "シンボル" {
        ===S1=== --> "つまり宗教
        <img: https://icooon-mono.com/i/icon_15071/icon_150711_64.png>"
        -> "伝統傾向"

        partition "彫刻" {
            "心の中のシンボルとして、あらゆる集団の理想。" -->===S1===
        }
        partition "本の象徴" {
            "理想の体現" --> "宗教的および専門的価値を表すもの
          
           <img:https://icooon-mono.com/i/icon_11238/icon_112381_64.png>" 
            --> ===S1===
        }
        partition "食器" {
            "民族的背景、先祖伝来の家財" --> "ここまで割れずに残ってきた"
            --> "それの存続自体が誇るべきことである。"
            --> "伝統
          <img:https://icooon-mono.com/i/icon_11172/icon_111721_64.png>"
            --> "変化傾向"
        }   
    }
      
    ===row_age=== --> "精神年齢"
    partition "子供の機能好き" {
            "思い出よりも機能を優先する" --> "椅子に対する感想
            <img: https://icooon-mono.com/i/icon_12744/icon_127441_64.png>"
            --> ===row_age=== 
    }
    partition "絵の価値" {
            "絵に対する反応"  --> "絵に価値を見出すのは力がいる 
        <img:https://icooon-mono.com/i/icon_16183/icon_161831_64.png>" 
        --> "二次元という形態に意味を見出すこと"
        --> "これに対する無関心と無能力"
        --> ===row_age=== 
    }


    partition "老人の思い出好" {
        "老人と家具" --> "大切な思い出や関係、過去の経験を見出している"
        "大切な思い出や関係、過去の経験を見出している" --> "性格"
    }
    partition "男性の理想努力" {
        "達成すべき努力理想を体現したもの" --> "プライド"
    }
    
    partition "ステレオの象徴" {
        "逃避や要求不満の発散（二番目が楽器）" --> "それが可能にする経験と事故との関連が大事"
        --> "他者との思い出などはまずあがらない"
        --> "自己中心的な快楽"
    }
  
    partition "楽器の象徴" {
        "能動的な動き" --> "多面的な経験"
    }

    partition "テレビの象徴" {
        "依存することによる罪悪感" --> "経験の受動的な会得"
        --> "自己と経験"
    }

    partition "植物の価値" {
        "養育、人の注意に反応する生き物の世話" --> "成長はその人の業績を表すトロフィーである"
        --> "自然界との結びつき"
        --> "自然への貢献"
    }

}


@enduml