@startuml 02color

partition "color" {

    "startcolor"  --> "color selection"

    "color selection" --> "white"
    partition "white" #white {
        "白" #white --> "「汚してはいけない」"
        "「汚してはいけない」" -> "強迫観念"
    }

    "color selection" --> "gray"
    partition "gray" #darkgray {
        "粘土の色" #darkgray --> "包み込むような安心感"
    }

    "color selection" --> "black"
    partition "black" #gray {
        "黒色を使う" --> "二つのパターンがある"
        If "目的" then
            --> [みんな使っているから] "ミーハー"
        else
            --> [汚れないから] "高い先見性と潔癖症"
            --> "計画性"
        Endif
    }

    "color selection" --> "blue"
    partition "blue" #dodgerblue {
        "青" --> "二面性を持つ" 
        If "スカイブルー" then
            --> [skyblue] "自然の豊かさ" #skyblue
        else
            --> [blue] "人工的な冷たさ" #blue
            --> "思考傾向"
        Endif
    }

    "color selection" --> "pink"
    partition "pink" #pink {
        "情熱の赤に" #red --> "純粋な白を混ぜた色" #white
        --> "青春の象徴"
    }
        
    "color selection" --> "red"
    partition "red" #red {
        "血の色"  --> "だから"
    }

}




@enduml