@startuml tempalte

namespace 観察{
    
    namespace 利き手 {
    }
    namespace 身なり {
        namespace 服装 {}
        namespace 腕時計 {}
    }
    観察.利き手 --> 観察.身なり

    namespace 嗜好 {
        namespace 色 {}
    }
    観察.身なり --> 観察.嗜好

    namespace 趣味 {
    }
    観察.嗜好 --> 観察.趣味


    namespace 何に反応するか {
        namespace 色か形か {
        }
        namespace どこを見ているのか {
        }
        namespace 目の動き {
        }
        namespace セリフ {
        }
    }
    観察.趣味 --> 観察.何に反応するか

    namespace 口癖 {

    }
    観察.何に反応するか --> 観察.口癖
    
}

namespace 照合{
    namespace 一般傾向{
        namespace 位置関係 {
            class 右{}
            class 左{}
        }
    }

    namespace 性格傾向{
        namespace 利き手 {
            class 右利き{
                一般人
            }
            class 左利き{
                変人
            }
        }

        namespace 趣味 {
            class ジャニオタ
        }
        観察.趣味 -> 照合.性格傾向.趣味
    }
    観察.利き手 -> 照合.性格傾向.利き手
}


@enduml